### PR TITLE
Running and finished simulations are now reported to experimenters

### PR DESCRIPTION
**Pull request by btruhand**

### CODE REVIEW

**Comment by btruhand** [comment]
Tell me if there's anything amiss Jorge. I know the UI's not great

**Comment by jorgearanda** [comment]
Thanks Btara, and sorry for the delay. I'll take a look at this pr tomorrow.

**Comment by jorgearanda** [comment]
Nice job, Btara. Besides the naming problems, the other thing I'd like you to polish a bit is the UI--to make it consistent with the style in the rest of the page. Thanks!

**Comment by btruhand** [comment]
Hi Jorge, sorry I missed the meeting. I was extremely fatigued from yesterday. About the UI, what do you think needs to be added/removed in particular so I have a grasp of what I need to do

**Comment by jorgearanda** [comment]
No worries, Btara. For the UI, try using the widgets that Bootstrap uses if you're not already, and perhaps try a table format like the rest of the tables in that page.

**Comment by btruhand** [comment]
So instead of making it a scrolling list you want me to make it into a table format? Would you want me then to let the table just continually grow, or do you want me to put a limit to the number of items shown there?

**Comment by jorgearanda** [comment]
Letting it continually grow is fine by now :-)

**Comment by btruhand** [comment]
Jorge, right now I have the information layed out side by side, one for running and finishing simulations the other planned to be for interrupted simulations. Do you want them to stay the same or have them be separated sections?

**Comment by jorgearanda** [comment]
I like the way it looks and does not clutter when it's side by side.

**Comment by btruhand** [comment]
I've made the changes Jorge. Also I've opened a new issue #201

**Comment by jorgearanda** [comment]
Great, thanks!

**Pull request merged**
