### PR TITLE
Ocean status options

### LINKED ISSUE #172: Ocean Status Table - Experimenter configurable ordering
The experimenters should be able to configure the ordering of the fishers in the ocean status table.

Ordering options should include:
- [ ] Static; current user on top
- [ ] Static; current user in middle
- [ ] Static; current user on bottom
- [ ] Dynamic; descending by fish caught this season
- [ ] Dynamic; descending by fish caught overall
- [ ] Dynamic; descending by $ this season
- [ ] Dynamic; descending by $ overall

### PR DESCRIPTION
**Pull request by James-Firth**
Closes #172 

The user's ocean status table sort-order is based the experiment's settings.

A few questions/issues:

1. Some text goes onto a new line but shrinking the 'Bot behaviour' column squishes the text, so is two lines acceptable or does that entire row need a re-work?
2. I noticed the admin side doesn't have localization strings, is that something we want to do? (should probably be a separate issue)
3. I'm unsure what behaviour we want for the radio buttons once the session is active. Should they still be changeable like other fields or disabled?

### CODE REVIEW

**Comment by jorgearanda** [comment]
Thanks James! First, an answer to your questions, and then comments on the commit:

1. I like the idea of keeping the new radio buttons where they are—they are an information display parameter. Maybe with a bit of copy editing it would look better; see below.
2. We've never asked to do localization for the researcher side. I've just added #187 in any case to keep track of that.
3. Disabled, but I've just noticed other stuff that should be disabled as well is not. #186.

**Comment by jorgearanda** [comment]
As for the pull request itself, great work! A couple of suggestions:
* Ocean Status Table Order -> Status Table Behaviour?
* Break into two dropdown boxes: Static/Dynamic, and then dynamically change the contents of the second (for example, if Static: Current user on top / Current user on middle, etc.)
* Perhaps bring the Status Table header to a regular font format style?

I should've realized before that the list of options on its own is kind of cluttered--sorry.

**Comment by James-Firth** [comment]
I updated this branch with master and implemented the changes you suggested as far as I understood them.

There's a dropdown to select between static and dynamic that reveals the proper options. 

I had initially set the header to an h3 tag since I felt it was a sub-category of the "Information Display" section, but the h4 looks really nice too. I assume that's what you meant by the 3rd bullet point?

Screenshot of changes:
image of new ui elements

**Comment by jorgearanda** [comment]
Thanks--I'll take a look tomorrow.

**Comment by jorgearanda** [comment]
Nice work, thanks!

**Pull request merged**
