### PR TITLE
Updated fish scss file with new colour scheme.

### LINKED ISSUE #160: [User] Colour Scheme
We should decide on a new colour scheme to be a little more visually pleasing.

Perhaps these? We discussed blues/greens being nice (and working well with the ocean theme!)

palette colours
http://www.materialpalette.com/light-blue/green 
```sass
/* Palette generated by Material Palette - materialpalette.com/light-blue/green */

$darkPrimaryColor:   #0288D1
$primaryColor:       #03A9F4
$lightPrimaryColor:  #B3E5FC
$textPrimaryColor:   #FFFFFF
$accentColor:        #4CAF50
$primaryTextColor:   #212121
$secondaryTextColor: #727272
$dividerColor:       #B6B6B6
```

### PR DESCRIPTION
**Pull request by James-Firth**
I added some background/font colours so the participant UI is all the proper shades of blue/green.

Also should we be including the *.css.map files? They don't seem to be in the gitignore file and I'm not sure what the best practice is regarding them.
Closes #160

### CODE REVIEW

**Comment by nsue** [comment]
I usually don't track the generated CSS sourcemap files in git, but some people do. This page does a good job explaining how they can be useful: https://developer.chrome.com/devtools/docs/css-preprocessors

**Comment by James-Firth** [comment]
Great thanks for the info Norm, I'll give it a read.

I'm fine tracking it or not, though I think I'd probably prefer not to since it's just a blob of data that'll get re-made if someone changes the stylesheet anyways (if I understand correctly). I just included them this time so we could discuss it.

If we decide not to we should make sure it's in the .gitignore file though.

I'll wait and see if @jorgearanda  has an opinion on it.

**Comment by jorgearanda** [comment]
Cool, thanks!

The only thing I don't like about not tracking the css files is that it adds a non-npm dependency for deploying fish (ruby and the sass gem), but we've already declared those as dependencies so it should be fine.

I'll just merge this and we can add the css to the gitignore file on a later commit.

**Comment by James-Firth** [comment]
@jorgearanda I think we could still track the .css to avoid that. But there's also a .css.map file, just not sure if we need that too

**Pull request merged**
